// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgxomzbzszuyaimyheqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJneG9temJ6c3p1eWFpbXloZXFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMTI3MjQsImV4cCI6MjA1ODY4ODcyNH0.8c-RKyZeTCoM_6DGS4G_2vLRibrxG7WIkR9_QNuu5Vo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);